/*
  Warnings:

  - The values [AVATAR_UPLOADED,AVATAR_REMOVED,POST_CREATED,POST_DELETED,COMMENT_ADDED,COMMENT_DELETED,BRUTE_FORCE_ATTEMPT,REQUEST_THROTTLED,MALICIOUS_PAYLOAD_DETECTED,SQL_INJECTION_ATTEMPT,XSS_ATTEMPT,IP_ALLOWLISTED,IP_BLACKLISTED,GEO_BLOCKED,UNUSUAL_LOCATION_DETECTED,API_KEY_CREATED,API_KEY_REVOKED,API_KEY_ABUSED,ENDPOINT_ABUSE_DETECTED,UNUSUAL_ACTIVITY_PATTERN,ADMIN_ACTION,CONFIG_UPDATED,SECURITY_SETTINGS_CHANGED] on the enum `AuditAction` will be removed. If these variants are still used in the database, this will fail.

*/
-- CreateEnum
CREATE TYPE "NotificationType" AS ENUM ('FOLLOW', 'UNFOLLOW', 'LIKE', 'COMMENT', 'MENTION', 'SHARE', 'MESSAGE', 'SYSTEM', 'ACHIEVEMENT', 'WELCOME');

-- AlterEnum
BEGIN;
CREATE TYPE "AuditAction_new" AS ENUM ('LOGIN_SUCCESS', 'LOGIN_FAILED', 'SIGNUP_SUCCESS', 'SIGNUP_FAILED', 'REFRESH_ROTATED', 'REFRESH_REUSED_DETECTED', 'TOKEN_ROTATED', 'LOGOUT', 'LOGOUT_ALL', 'PASSWORD_RESET_REQUEST', 'PASSWORD_RESET_COMPLETED', 'EMAIL_VERIFICATION_SENT', 'EMAIL_VERIFIED', 'TOKEN_REVOKED_MANUALLY', 'PROFILE_VIEWED', 'PROFILE_UPDATED', 'ACCOUNT_DELETED', 'RATE_LIMIT_EXCEEDED', 'RATE_LIMIT_BYPASS_ATTEMPT', 'RATE_LIMIT_RESET', 'BOT_DETECTED', 'BOT_CHALLENGED', 'BOT_BLOCKED', 'SUSPICIOUS_ACTIVITY', 'CSRF_ATTEMPT', 'IP_BLOCKED', 'ADMIN_LOGIN', 'ACCOUNT_DELETED_BY_ADMIN');
ALTER TABLE "AuditLog" ALTER COLUMN "action" TYPE "AuditAction_new" USING ("action"::text::"AuditAction_new");
ALTER TYPE "AuditAction" RENAME TO "AuditAction_old";
ALTER TYPE "AuditAction_new" RENAME TO "AuditAction";
DROP TYPE "public"."AuditAction_old";
COMMIT;

-- CreateTable
CREATE TABLE "Notification" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "fromId" TEXT NOT NULL,
    "type" "NotificationType" NOT NULL,
    "read" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Notification_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "Notification" ADD CONSTRAINT "Notification_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Notification" ADD CONSTRAINT "Notification_fromId_fkey" FOREIGN KEY ("fromId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
