import { MigrationInterface, QueryRunner } from "typeorm";

export class Migrations1763968479153 implements MigrationInterface {
    name = 'Migrations1763968479153'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "email_tokens" DROP CONSTRAINT "FK_0a5e6c81093655b770eabd04600"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP CONSTRAINT "FK_610102b60fea1455310ccd299de"`);
        await queryRunner.query(`ALTER TABLE "email_tokens" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "email_tokens" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "email_tokens" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "email_tokens" DROP COLUMN "tokenHash"`);
        await queryRunner.query(`ALTER TABLE "email_tokens" DROP COLUMN "expiresAt"`);
        await queryRunner.query(`ALTER TABLE "email_tokens" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP COLUMN "tokenId"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP COLUMN "hashedToken"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP COLUMN "expiresAt"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP COLUMN "lastUsedAt"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP COLUMN "userAgent"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "firstName"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "avatarPublicId"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "lastName"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "passwordHash"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "emailVerified"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "riskEvent"`);
        await queryRunner.query(`DROP TYPE "public"."audit_logs_riskevent_enum"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "userAgent"`);
        await queryRunner.query(`ALTER TABLE "email_tokens" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "email_tokens" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "email_tokens" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "email_tokens" ADD "token_hash" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "email_tokens" ADD "expires_at" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "email_tokens" ADD "user_id" uuid`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD "token_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD "hashed_token" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD "expires_at" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD "last_used_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD "user_agent" character varying`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD "user_id" uuid`);
        await queryRunner.query(`ALTER TABLE "users" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "users" ADD "first_name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD "avatar_public_id" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD "last_name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD "password_hash" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD "email_verified" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`CREATE TYPE "public"."audit_logs_risk_event_enum" AS ENUM('ABUSE', 'ANOMALY', 'BRUTE_FORCE', 'TOKEN_REUSE', 'RATE_LIMIT_TRIGGERED', 'POSSIBLE_COMPROMISE')`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "risk_event" "public"."audit_logs_risk_event_enum"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "user_id" character varying`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "user_agent" character varying`);
        await queryRunner.query(`ALTER TABLE "email_tokens" ADD CONSTRAINT "FK_018295f41628791c301bfe8b625" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD CONSTRAINT "FK_3ddc983c5f7bcf132fd8732c3f4" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP CONSTRAINT "FK_3ddc983c5f7bcf132fd8732c3f4"`);
        await queryRunner.query(`ALTER TABLE "email_tokens" DROP CONSTRAINT "FK_018295f41628791c301bfe8b625"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "user_agent"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "risk_event"`);
        await queryRunner.query(`DROP TYPE "public"."audit_logs_risk_event_enum"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "email_verified"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "password_hash"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "last_name"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "avatar_public_id"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "first_name"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP COLUMN "user_agent"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP COLUMN "last_used_at"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP COLUMN "expires_at"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP COLUMN "hashed_token"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP COLUMN "token_id"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "email_tokens" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "email_tokens" DROP COLUMN "expires_at"`);
        await queryRunner.query(`ALTER TABLE "email_tokens" DROP COLUMN "token_hash"`);
        await queryRunner.query(`ALTER TABLE "email_tokens" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "email_tokens" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "email_tokens" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "userAgent" character varying`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "userId" character varying`);
        await queryRunner.query(`CREATE TYPE "public"."audit_logs_riskevent_enum" AS ENUM('ABUSE', 'ANOMALY', 'BRUTE_FORCE', 'TOKEN_REUSE', 'RATE_LIMIT_TRIGGERED', 'POSSIBLE_COMPROMISE')`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "riskEvent" "public"."audit_logs_riskevent_enum"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" ADD "emailVerified" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "users" ADD "passwordHash" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD "lastName" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD "avatarPublicId" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD "firstName" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "users" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD "userId" uuid`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD "userAgent" character varying`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD "lastUsedAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD "expiresAt" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD "hashedToken" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD "tokenId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "email_tokens" ADD "userId" uuid`);
        await queryRunner.query(`ALTER TABLE "email_tokens" ADD "expiresAt" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "email_tokens" ADD "tokenHash" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "email_tokens" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "email_tokens" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "email_tokens" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD CONSTRAINT "FK_610102b60fea1455310ccd299de" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "email_tokens" ADD CONSTRAINT "FK_0a5e6c81093655b770eabd04600" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
