import { MigrationInterface, QueryRunner } from "typeorm";

export class Migrations1764334082526 implements MigrationInterface {
    name = 'Migrations1764334082526'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."email_tokens_type_enum" AS ENUM('VERIFY', 'RESET')`);
        await queryRunner.query(`CREATE TABLE "email_tokens" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "token_hash" character varying NOT NULL, "type" "public"."email_tokens_type_enum" NOT NULL, "expires_at" TIMESTAMP NOT NULL, "used" boolean NOT NULL DEFAULT false, "user_id" uuid, CONSTRAINT "PK_08abb3fa348e894c274a6730d35" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "refresh_tokens" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "token_id" character varying NOT NULL, "hashed_token" character varying NOT NULL, "expires_at" TIMESTAMP NOT NULL, "revoked" boolean NOT NULL DEFAULT false, "last_used_at" TIMESTAMP, "ip" character varying, "user_agent" character varying, "user_id" uuid, CONSTRAINT "PK_7d8bee0204106019488c4c50ffa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "like" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "user_id" uuid NOT NULL, "post_id" uuid NOT NULL, CONSTRAINT "PK_eff3e46d24d416b52a7e0ae4159" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_521766c01050bef30e5600c4b2" ON "like" ("created_at") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_3221edd468ef18cc93a806b74b" ON "like" ("post_id", "user_id") `);
        await queryRunner.query(`CREATE TABLE "bookmark" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "user_id" uuid NOT NULL, "post_id" uuid NOT NULL, CONSTRAINT "PK_b7fbf4a865ba38a590bb9239814" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_889e0abce86f466db2488ad739" ON "bookmark" ("user_id", "created_at") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_9835db6ee07225b1b2fad9943e" ON "bookmark" ("post_id", "user_id") `);
        await queryRunner.query(`CREATE TABLE "media" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "public_id" character varying NOT NULL, "media_url" character varying NOT NULL, "resource_type" character varying NOT NULL, "post_id" uuid, "reply_id" uuid, CONSTRAINT "PK_f4e0fcac36e050de337b670d8bd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "mention" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "read" boolean NOT NULL DEFAULT false, "post_id" uuid, "reply_id" uuid, "mentioned_user_id" uuid, "author_id" uuid, CONSTRAINT "PK_9b02b76c4b65e3c35c1a545bf57" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8e1152672957ae8312354ff22c" ON "mention" ("reply_id", "mentioned_user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_1815b34ed24c6feee36cb66360" ON "mention" ("post_id", "mentioned_user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_6e8df8e05e93dc408065071130" ON "mention" ("mentioned_user_id", "created_at") `);
        await queryRunner.query(`CREATE TABLE "reply" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "content" text NOT NULL, "post_id" uuid NOT NULL, "author_id" uuid NOT NULL, "reply_count" integer NOT NULL DEFAULT '0', "parent_reply_id" uuid, CONSTRAINT "PK_94fa9017051b40a71e000a2aff9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7dc106312b0d9f111acf7ca02a" ON "reply" ("author_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_3cf30b2d2c2249ec410b84ecdd" ON "reply" ("post_id", "created_at") `);
        await queryRunner.query(`CREATE TABLE "repost" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "content" text, "user_id" uuid NOT NULL, "original_post_id" uuid NOT NULL, CONSTRAINT "PK_abfcbb696914c514fca81f8cc0b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3f023b8dc80e2609d8dce8d22c" ON "repost" ("original_post_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_d2fee25ddac8d9798081cffe7c" ON "repost" ("user_id", "created_at") `);
        await queryRunner.query(`CREATE TABLE "hashtag" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "tag" character varying NOT NULL, "usage_count" integer NOT NULL DEFAULT '0', "post_count" integer NOT NULL DEFAULT '0', "trend_score" integer NOT NULL DEFAULT '0', "last_used_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_d08e011257d7cba6df34c553133" UNIQUE ("tag"), CONSTRAINT "PK_cb36eb8af8412bfa978f1165d78" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_dd688373931824f98e4e48f22f" ON "hashtag" ("usage_count") `);
        await queryRunner.query(`CREATE INDEX "IDX_d08e011257d7cba6df34c55313" ON "hashtag" ("tag") `);
        await queryRunner.query(`CREATE TABLE "post_hashtag" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "post_id" character varying NOT NULL, "hashtag_id" character varying NOT NULL, "postId" uuid, "hashtagId" uuid, CONSTRAINT "PK_b2b81130921679b878f6c5495d7" PRIMARY KEY ("id", "post_id", "hashtag_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d3d78c80aedd7605863b5d1f14" ON "post_hashtag" ("postId", "hashtagId") `);
        await queryRunner.query(`CREATE INDEX "IDX_caefca8a8185da9609bd364eaa" ON "post_hashtag" ("hashtagId", "created_at") `);
        await queryRunner.query(`CREATE TYPE "public"."post_visibility_enum" AS ENUM('public', 'followers', 'private')`);
        await queryRunner.query(`CREATE TABLE "post" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "content" text, "visibility" "public"."post_visibility_enum" NOT NULL DEFAULT 'public', "author_id" uuid NOT NULL, "like_count" integer NOT NULL DEFAULT '0', "reply_count" integer NOT NULL DEFAULT '0', "repost_count" integer NOT NULL DEFAULT '0', "view_count" integer NOT NULL DEFAULT '0', "media_count" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_be5fda3aac270b134ff9c21cdee" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a80ca3bf4ca3711c488cb82cf7" ON "post" ("visibility") `);
        await queryRunner.query(`CREATE INDEX "IDX_0f8f2f0c0512fbecbe3034b804" ON "post" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_9bf357e95bffead052c455f46c" ON "post" ("author_id", "visibility", "created_at") `);
        await queryRunner.query(`CREATE TABLE "notification_preferences" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "user_id" uuid NOT NULL, "likes" boolean NOT NULL DEFAULT true, "posts" boolean NOT NULL DEFAULT true, "replies" boolean NOT NULL DEFAULT true, "reposts" boolean NOT NULL DEFAULT true, "follows" boolean NOT NULL DEFAULT true, "mentions" boolean NOT NULL DEFAULT true, "system" boolean NOT NULL DEFAULT true, "email_likes" boolean NOT NULL DEFAULT false, "email_replies" boolean NOT NULL DEFAULT false, "email_reposts" boolean NOT NULL DEFAULT false, "email_follows" boolean NOT NULL DEFAULT false, "email_mentions" boolean NOT NULL DEFAULT false, "email_system" boolean NOT NULL DEFAULT true, "email_digest" boolean NOT NULL DEFAULT true, "push_likes" boolean NOT NULL DEFAULT true, "push_replies" boolean NOT NULL DEFAULT true, "push_reposts" boolean NOT NULL DEFAULT true, "push_follows" boolean NOT NULL DEFAULT true, "push_mentions" boolean NOT NULL DEFAULT true, "push_system" boolean NOT NULL DEFAULT true, "sound_enabled" boolean NOT NULL DEFAULT true, "vibration_enabled" boolean NOT NULL DEFAULT true, "delivery_timing" character varying NOT NULL DEFAULT 'immediate', "muted_users" jsonb NOT NULL DEFAULT '{}', "muted_keywords" jsonb NOT NULL DEFAULT '{}', CONSTRAINT "REL_64c90edc7310c6be7c10c96f67" UNIQUE ("user_id"), CONSTRAINT "PK_e94e2b543f2f218ee68e4f4fad2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('user', 'admin')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "email" character varying NOT NULL, "username" character varying(100) NOT NULL, "first_name" character varying NOT NULL, "avatar" character varying, "avatar_public_id" character varying, "last_name" character varying NOT NULL, "bio" character varying, "website" character varying, "location" character varying, "resource_type" character varying, "password_hash" character varying NOT NULL, "email_verified" boolean NOT NULL DEFAULT false, "role" "public"."users_role_enum" NOT NULL DEFAULT 'user', CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710" UNIQUE ("username"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "follows" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "following_id" uuid NOT NULL, "follower_id" uuid NOT NULL, CONSTRAINT "UQ_8109e59f691f0444b43420f6987" UNIQUE ("follower_id", "following_id"), CONSTRAINT "PK_8988f607744e16ff79da3b8a627" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."notification_type_enum" AS ENUM('LIKE', 'REPLY', 'REPOST', 'FOLLOW', 'MENTION', 'SYSTEM')`);
        await queryRunner.query(`CREATE TABLE "notification" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "type" "public"."notification_type_enum" NOT NULL, "post_id" uuid, "reply_id" uuid, "read" boolean NOT NULL DEFAULT false, "metadata" jsonb, "recipient_id" uuid, "actor_id" uuid, CONSTRAINT "PK_705b6c7cdf9b2c2ff7ac7872cb7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_20b88691d81274bbfce4a037f5" ON "notification" ("recipient_id", "type", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_4ceacc6224f42136fecf68e89e" ON "notification" ("recipient_id", "read", "created_at") `);
        await queryRunner.query(`CREATE TYPE "public"."audit_logs_action_enum" AS ENUM('SIGNUP', 'LOGIN', 'LOGOUT', 'REFRESH_TOKEN_ROTATED', 'PASSWORD_RESET_REQUEST', 'PASSWORD_RESET_COMPLETED', 'EMAIL_VERIFICATION_SENT', 'EMAIL_VERIFIED', 'FAILED_LOGIN', 'REUSED_REFRESH_TOKEN', 'RATE_LIMITED', 'SUSPICIOUS_ACTIVITY', 'USER_UPDATED', 'USER_DELETED', 'PROFILE_VIEWED', 'USER_FOLLOWED', 'USER_UNFOLLOWED', 'PROFILE_VIEWED_FOLLOWERS', 'POST_CREATED', 'POST_VIEWED', 'POST_UPDATED', 'POST_DELETED', 'REPLY_CREATED', 'REPOST_CREATED', 'POST_UNLIKED', 'POST_LIKED', 'POST_BOOKMARKED', 'POST_UNBOOKMARKED', 'POST_REPOSTED', 'POST_UNREPOSTED', 'REPLY_DELETED', 'REPLY_UPDATED')`);
        await queryRunner.query(`CREATE TYPE "public"."audit_logs_resource_enum" AS ENUM('AUTH', 'USER', 'POST', 'REPLY', 'REPOST')`);
        await queryRunner.query(`CREATE TYPE "public"."audit_logs_risk_event_enum" AS ENUM('ABUSE', 'ANOMALY', 'BRUTE_FORCE', 'TOKEN_REUSE', 'RATE_LIMIT_TRIGGERED', 'POSSIBLE_COMPROMISE')`);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "action" "public"."audit_logs_action_enum" NOT NULL, "resource" "public"."audit_logs_resource_enum", "risk_event" "public"."audit_logs_risk_event_enum", "user_id" character varying, "ip" character varying, "user_agent" character varying, "metadata" jsonb, CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "email_tokens" ADD CONSTRAINT "FK_018295f41628791c301bfe8b625" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD CONSTRAINT "FK_3ddc983c5f7bcf132fd8732c3f4" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "like" ADD CONSTRAINT "FK_4356ac2f9519c7404a2869f1691" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "like" ADD CONSTRAINT "FK_d41caa70371e578e2a4791a88ae" FOREIGN KEY ("post_id") REFERENCES "post"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookmark" ADD CONSTRAINT "FK_88d15be9a11888c73c7328a32fc" FOREIGN KEY ("post_id") REFERENCES "post"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookmark" ADD CONSTRAINT "FK_8f1a143c6ba8bba0e2a4f41e0d0" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "media" ADD CONSTRAINT "FK_20dc152fa567df67110b94d6f16" FOREIGN KEY ("post_id") REFERENCES "post"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "media" ADD CONSTRAINT "FK_a06d5fc3cbf364e3f7fe08f1350" FOREIGN KEY ("reply_id") REFERENCES "reply"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mention" ADD CONSTRAINT "FK_1ceda53d50bbc68711ead73632a" FOREIGN KEY ("post_id") REFERENCES "post"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mention" ADD CONSTRAINT "FK_4533a736e6038b6de35d50befae" FOREIGN KEY ("reply_id") REFERENCES "reply"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mention" ADD CONSTRAINT "FK_17edd318132abe43dcc02106d8d" FOREIGN KEY ("mentioned_user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mention" ADD CONSTRAINT "FK_56116d97f4485e37b82685fd9bc" FOREIGN KEY ("author_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reply" ADD CONSTRAINT "FK_26661bdd4c8727e914b5f2b10b5" FOREIGN KEY ("post_id") REFERENCES "post"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reply" ADD CONSTRAINT "FK_0d98e8ade07b472e8af8b856e1b" FOREIGN KEY ("author_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reply" ADD CONSTRAINT "FK_52950ff18c5841b7c67f1504b0f" FOREIGN KEY ("parent_reply_id") REFERENCES "reply"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "repost" ADD CONSTRAINT "FK_2aab7c4ee36af12259c641825b8" FOREIGN KEY ("original_post_id") REFERENCES "post"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "repost" ADD CONSTRAINT "FK_59ab6efd4621bf07bd72e697e82" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post_hashtag" ADD CONSTRAINT "FK_6b41c908e59dd1c45518efa4291" FOREIGN KEY ("postId") REFERENCES "post"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post_hashtag" ADD CONSTRAINT "FK_5e6bd8131c5321b4dbf68f1ce5f" FOREIGN KEY ("hashtagId") REFERENCES "hashtag"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post" ADD CONSTRAINT "FK_2f1a9ca8908fc8168bc18437f62" FOREIGN KEY ("author_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification_preferences" ADD CONSTRAINT "FK_64c90edc7310c6be7c10c96f675" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "follows" ADD CONSTRAINT "FK_54b5dc2739f2dea57900933db66" FOREIGN KEY ("follower_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "follows" ADD CONSTRAINT "FK_c518e3988b9c057920afaf2d8c0" FOREIGN KEY ("following_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification" ADD CONSTRAINT "FK_9830357f52360a126737d498e66" FOREIGN KEY ("recipient_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification" ADD CONSTRAINT "FK_16addcdc44128a517daeddd4491" FOREIGN KEY ("actor_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification" ADD CONSTRAINT "FK_3ee113bf568b5efdc29cd95a360" FOREIGN KEY ("post_id") REFERENCES "post"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification" ADD CONSTRAINT "FK_a2559f02e2a4fec5eae362a4c00" FOREIGN KEY ("reply_id") REFERENCES "reply"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "notification" DROP CONSTRAINT "FK_a2559f02e2a4fec5eae362a4c00"`);
        await queryRunner.query(`ALTER TABLE "notification" DROP CONSTRAINT "FK_3ee113bf568b5efdc29cd95a360"`);
        await queryRunner.query(`ALTER TABLE "notification" DROP CONSTRAINT "FK_16addcdc44128a517daeddd4491"`);
        await queryRunner.query(`ALTER TABLE "notification" DROP CONSTRAINT "FK_9830357f52360a126737d498e66"`);
        await queryRunner.query(`ALTER TABLE "follows" DROP CONSTRAINT "FK_c518e3988b9c057920afaf2d8c0"`);
        await queryRunner.query(`ALTER TABLE "follows" DROP CONSTRAINT "FK_54b5dc2739f2dea57900933db66"`);
        await queryRunner.query(`ALTER TABLE "notification_preferences" DROP CONSTRAINT "FK_64c90edc7310c6be7c10c96f675"`);
        await queryRunner.query(`ALTER TABLE "post" DROP CONSTRAINT "FK_2f1a9ca8908fc8168bc18437f62"`);
        await queryRunner.query(`ALTER TABLE "post_hashtag" DROP CONSTRAINT "FK_5e6bd8131c5321b4dbf68f1ce5f"`);
        await queryRunner.query(`ALTER TABLE "post_hashtag" DROP CONSTRAINT "FK_6b41c908e59dd1c45518efa4291"`);
        await queryRunner.query(`ALTER TABLE "repost" DROP CONSTRAINT "FK_59ab6efd4621bf07bd72e697e82"`);
        await queryRunner.query(`ALTER TABLE "repost" DROP CONSTRAINT "FK_2aab7c4ee36af12259c641825b8"`);
        await queryRunner.query(`ALTER TABLE "reply" DROP CONSTRAINT "FK_52950ff18c5841b7c67f1504b0f"`);
        await queryRunner.query(`ALTER TABLE "reply" DROP CONSTRAINT "FK_0d98e8ade07b472e8af8b856e1b"`);
        await queryRunner.query(`ALTER TABLE "reply" DROP CONSTRAINT "FK_26661bdd4c8727e914b5f2b10b5"`);
        await queryRunner.query(`ALTER TABLE "mention" DROP CONSTRAINT "FK_56116d97f4485e37b82685fd9bc"`);
        await queryRunner.query(`ALTER TABLE "mention" DROP CONSTRAINT "FK_17edd318132abe43dcc02106d8d"`);
        await queryRunner.query(`ALTER TABLE "mention" DROP CONSTRAINT "FK_4533a736e6038b6de35d50befae"`);
        await queryRunner.query(`ALTER TABLE "mention" DROP CONSTRAINT "FK_1ceda53d50bbc68711ead73632a"`);
        await queryRunner.query(`ALTER TABLE "media" DROP CONSTRAINT "FK_a06d5fc3cbf364e3f7fe08f1350"`);
        await queryRunner.query(`ALTER TABLE "media" DROP CONSTRAINT "FK_20dc152fa567df67110b94d6f16"`);
        await queryRunner.query(`ALTER TABLE "bookmark" DROP CONSTRAINT "FK_8f1a143c6ba8bba0e2a4f41e0d0"`);
        await queryRunner.query(`ALTER TABLE "bookmark" DROP CONSTRAINT "FK_88d15be9a11888c73c7328a32fc"`);
        await queryRunner.query(`ALTER TABLE "like" DROP CONSTRAINT "FK_d41caa70371e578e2a4791a88ae"`);
        await queryRunner.query(`ALTER TABLE "like" DROP CONSTRAINT "FK_4356ac2f9519c7404a2869f1691"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP CONSTRAINT "FK_3ddc983c5f7bcf132fd8732c3f4"`);
        await queryRunner.query(`ALTER TABLE "email_tokens" DROP CONSTRAINT "FK_018295f41628791c301bfe8b625"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP TYPE "public"."audit_logs_risk_event_enum"`);
        await queryRunner.query(`DROP TYPE "public"."audit_logs_resource_enum"`);
        await queryRunner.query(`DROP TYPE "public"."audit_logs_action_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4ceacc6224f42136fecf68e89e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_20b88691d81274bbfce4a037f5"`);
        await queryRunner.query(`DROP TABLE "notification"`);
        await queryRunner.query(`DROP TYPE "public"."notification_type_enum"`);
        await queryRunner.query(`DROP TABLE "follows"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`DROP TABLE "notification_preferences"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9bf357e95bffead052c455f46c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0f8f2f0c0512fbecbe3034b804"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a80ca3bf4ca3711c488cb82cf7"`);
        await queryRunner.query(`DROP TABLE "post"`);
        await queryRunner.query(`DROP TYPE "public"."post_visibility_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_caefca8a8185da9609bd364eaa"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d3d78c80aedd7605863b5d1f14"`);
        await queryRunner.query(`DROP TABLE "post_hashtag"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d08e011257d7cba6df34c55313"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dd688373931824f98e4e48f22f"`);
        await queryRunner.query(`DROP TABLE "hashtag"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d2fee25ddac8d9798081cffe7c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3f023b8dc80e2609d8dce8d22c"`);
        await queryRunner.query(`DROP TABLE "repost"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3cf30b2d2c2249ec410b84ecdd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7dc106312b0d9f111acf7ca02a"`);
        await queryRunner.query(`DROP TABLE "reply"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6e8df8e05e93dc408065071130"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1815b34ed24c6feee36cb66360"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8e1152672957ae8312354ff22c"`);
        await queryRunner.query(`DROP TABLE "mention"`);
        await queryRunner.query(`DROP TABLE "media"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9835db6ee07225b1b2fad9943e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_889e0abce86f466db2488ad739"`);
        await queryRunner.query(`DROP TABLE "bookmark"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3221edd468ef18cc93a806b74b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_521766c01050bef30e5600c4b2"`);
        await queryRunner.query(`DROP TABLE "like"`);
        await queryRunner.query(`DROP TABLE "refresh_tokens"`);
        await queryRunner.query(`DROP TABLE "email_tokens"`);
        await queryRunner.query(`DROP TYPE "public"."email_tokens_type_enum"`);
    }

}
