import { MigrationInterface, QueryRunner } from "typeorm";

export class Migrations1764101156612 implements MigrationInterface {
    name = 'Migrations1764101156612'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "email_tokens" DROP CONSTRAINT "FK_0a5e6c81093655b770eabd04600"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP CONSTRAINT "FK_610102b60fea1455310ccd299de"`);
        await queryRunner.query(`ALTER TABLE "like" DROP CONSTRAINT "FK_3acf7c55c319c4000e8056c1279"`);
        await queryRunner.query(`ALTER TABLE "like" DROP CONSTRAINT "FK_e8fb739f08d47955a39850fac23"`);
        await queryRunner.query(`ALTER TABLE "bookmark" DROP CONSTRAINT "FK_e389fc192c59bdce0847ef9ef8b"`);
        await queryRunner.query(`ALTER TABLE "bookmark" DROP CONSTRAINT "FK_ee4a9b84b65399f9a6581d9a9a5"`);
        await queryRunner.query(`ALTER TABLE "media" DROP CONSTRAINT "FK_d9e592b7c68d3aab7582e28a06a"`);
        await queryRunner.query(`ALTER TABLE "media" DROP CONSTRAINT "FK_9dcde1b1308b5f22f34b8454e28"`);
        await queryRunner.query(`ALTER TABLE "mention" DROP CONSTRAINT "FK_d2f967c23ec5174f12c53ee6712"`);
        await queryRunner.query(`ALTER TABLE "mention" DROP CONSTRAINT "FK_16a2deee0d7ea361950eed1b944"`);
        await queryRunner.query(`ALTER TABLE "mention" DROP CONSTRAINT "FK_ff19b87c8b552823b87abf5c7af"`);
        await queryRunner.query(`ALTER TABLE "mention" DROP CONSTRAINT "FK_6e47473e7777212acf0f1f10e66"`);
        await queryRunner.query(`ALTER TABLE "reply" DROP CONSTRAINT "FK_f0af68fe0e599c7cc7f34699ad5"`);
        await queryRunner.query(`ALTER TABLE "reply" DROP CONSTRAINT "FK_9c7aa85b4b2be67c1b7235d03fe"`);
        await queryRunner.query(`ALTER TABLE "reply" DROP CONSTRAINT "FK_650bb493bc96cdc1c6a95d50ccd"`);
        await queryRunner.query(`ALTER TABLE "repost" DROP CONSTRAINT "FK_d485b70d5447a47d8ebcb815920"`);
        await queryRunner.query(`ALTER TABLE "repost" DROP CONSTRAINT "FK_1398d4509dfe620c68724aeff30"`);
        await queryRunner.query(`ALTER TABLE "post_hashtag" DROP CONSTRAINT "FK_5e6bd8131c5321b4dbf68f1ce5f"`);
        await queryRunner.query(`ALTER TABLE "post_hashtag" DROP CONSTRAINT "FK_6b41c908e59dd1c45518efa4291"`);
        await queryRunner.query(`ALTER TABLE "post" DROP CONSTRAINT "FK_c6fb082a3114f35d0cc27c518e0"`);
        await queryRunner.query(`ALTER TABLE "follows" DROP CONSTRAINT "FK_ef463dd9a2ce0d673350e36e0fb"`);
        await queryRunner.query(`ALTER TABLE "follows" DROP CONSTRAINT "FK_fdb91868b03a2040db408a53331"`);
        await queryRunner.query(`ALTER TABLE "r_like" DROP CONSTRAINT "FK_a3ae0bfcdccb98ba91508574eb1"`);
        await queryRunner.query(`ALTER TABLE "r_like" DROP CONSTRAINT "FK_10ac8c44e53eb105de83c8b63c8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_78a9f4a1b09b6d2bf7ed85f252"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ca9645f823ed33ad823063b35b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b6aae0d8a415c27308fe51c837"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9e9632e3b6afa29ac5bb84a5d5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ad94e8d3b6b2525d4980f960cd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f997b5003d8b22a0ec0902e55c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_81e9616cb4c5c0f18ec277950b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2ae88db6d7f193e004ee1d9794"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c5a573b830502bf341d9ec9803"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5c73da33047a8e7f862fbd65c9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_07a8923e0c3543fb9c6bc2e35c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_251105b046faae0f8740ab39cb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d3d78c80aedd7605863b5d1f14"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fc550e52604301a6fcc23183e9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fb91bea2d37140a877b775e6b2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_333b5b35488ffbf401d0728b46"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ab7f82381f392d8c38ec5fc537"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0c2bb4798c44b15d5b92b62b33"`);
        await queryRunner.query(`ALTER TABLE "follows" DROP CONSTRAINT "UQ_105079775692df1f8799ed0fac8"`);
        await queryRunner.query(`ALTER TABLE "email_tokens" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "email_tokens" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "email_tokens" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "email_tokens" DROP COLUMN "expiresAt"`);
        await queryRunner.query(`ALTER TABLE "email_tokens" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "email_tokens" DROP COLUMN "tokenHash"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP COLUMN "expiresAt"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP COLUMN "lastUsedAt"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP COLUMN "tokenId"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP COLUMN "hashedToken"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP COLUMN "userAgent"`);
        await queryRunner.query(`ALTER TABLE "like" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "like" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "like" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "like" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "like" DROP COLUMN "postId"`);
        await queryRunner.query(`ALTER TABLE "bookmark" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "bookmark" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "bookmark" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "bookmark" DROP COLUMN "postId"`);
        await queryRunner.query(`ALTER TABLE "bookmark" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "media" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "media" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "media" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "media" DROP COLUMN "postId"`);
        await queryRunner.query(`ALTER TABLE "media" DROP COLUMN "replyId"`);
        await queryRunner.query(`ALTER TABLE "media" DROP COLUMN "publicId"`);
        await queryRunner.query(`ALTER TABLE "media" DROP COLUMN "mediaUrl"`);
        await queryRunner.query(`ALTER TABLE "media" DROP COLUMN "resourceType"`);
        await queryRunner.query(`ALTER TABLE "mention" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "mention" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "mention" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "mention" DROP COLUMN "mentionedUserId"`);
        await queryRunner.query(`ALTER TABLE "mention" DROP COLUMN "authorId"`);
        await queryRunner.query(`ALTER TABLE "mention" DROP COLUMN "postId"`);
        await queryRunner.query(`ALTER TABLE "mention" DROP COLUMN "replyId"`);
        await queryRunner.query(`ALTER TABLE "reply" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "reply" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "reply" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "reply" DROP COLUMN "postId"`);
        await queryRunner.query(`ALTER TABLE "reply" DROP COLUMN "authorId"`);
        await queryRunner.query(`ALTER TABLE "reply" DROP COLUMN "replyCount"`);
        await queryRunner.query(`ALTER TABLE "reply" DROP COLUMN "parentReplyId"`);
        await queryRunner.query(`ALTER TABLE "repost" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "repost" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "repost" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "repost" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "repost" DROP COLUMN "originalPostId"`);
        await queryRunner.query(`ALTER TABLE "hashtag" DROP COLUMN "postCount"`);
        await queryRunner.query(`ALTER TABLE "hashtag" DROP COLUMN "trendScore"`);
        await queryRunner.query(`ALTER TABLE "hashtag" DROP COLUMN "lastUsedAt"`);
        await queryRunner.query(`ALTER TABLE "hashtag" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "hashtag" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "hashtag" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "hashtag" DROP COLUMN "usageCount"`);
        await queryRunner.query(`ALTER TABLE "post_hashtag" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "post_hashtag" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "post_hashtag" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "post_hashtag" DROP COLUMN "postId"`);
        await queryRunner.query(`ALTER TABLE "post_hashtag" DROP COLUMN "hashtagId"`);
        await queryRunner.query(`ALTER TABLE "post" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "post" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "post" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "post" DROP COLUMN "authorId"`);
        await queryRunner.query(`ALTER TABLE "post" DROP COLUMN "likeCount"`);
        await queryRunner.query(`ALTER TABLE "post" DROP COLUMN "replyCount"`);
        await queryRunner.query(`ALTER TABLE "post" DROP COLUMN "repostCount"`);
        await queryRunner.query(`ALTER TABLE "post" DROP COLUMN "viewCount"`);
        await queryRunner.query(`ALTER TABLE "post" DROP COLUMN "mediaCount"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "emailVerified"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "avatarPublicId"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "lastName"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "passwordHash"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "resourceType"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "firstName"`);
        await queryRunner.query(`ALTER TABLE "follows" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "follows" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "follows" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "follows" DROP COLUMN "followerId"`);
        await queryRunner.query(`ALTER TABLE "follows" DROP COLUMN "followingId"`);
        await queryRunner.query(`ALTER TABLE "r_like" DROP COLUMN "replyId"`);
        await queryRunner.query(`ALTER TABLE "r_like" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "r_like" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "r_like" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "r_like" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "r_like" DROP COLUMN "postId"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "riskEvent"`);
        await queryRunner.query(`DROP TYPE "public"."audit_logs_riskevent_enum"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "userAgent"`);
        await queryRunner.query(`ALTER TABLE "email_tokens" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "email_tokens" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "email_tokens" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "email_tokens" ADD "token_hash" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "email_tokens" ADD "expires_at" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "email_tokens" ADD "user_id" uuid`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD "token_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD "hashed_token" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD "expires_at" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD "last_used_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD "user_agent" character varying`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD "user_id" uuid`);
        await queryRunner.query(`ALTER TABLE "like" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "like" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "like" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "like" ADD "user_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "like" ADD "post_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "bookmark" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "bookmark" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "bookmark" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "bookmark" ADD "user_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "bookmark" ADD "post_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "media" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "media" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "media" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "media" ADD "public_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "media" ADD "media_url" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "media" ADD "resource_type" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "media" ADD "post_id" uuid`);
        await queryRunner.query(`ALTER TABLE "media" ADD "reply_id" uuid`);
        await queryRunner.query(`ALTER TABLE "mention" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "mention" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "mention" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "mention" ADD "post_id" uuid`);
        await queryRunner.query(`ALTER TABLE "mention" ADD "reply_id" uuid`);
        await queryRunner.query(`ALTER TABLE "mention" ADD "mentioned_user_id" uuid`);
        await queryRunner.query(`ALTER TABLE "mention" ADD "author_id" uuid`);
        await queryRunner.query(`ALTER TABLE "reply" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "reply" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "reply" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "reply" ADD "post_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "reply" ADD "author_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "reply" ADD "reply_count" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "reply" ADD "parent_reply_id" uuid`);
        await queryRunner.query(`ALTER TABLE "repost" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "repost" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "repost" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "repost" ADD "user_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "repost" ADD "original_post_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "hashtag" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "hashtag" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "hashtag" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "hashtag" ADD "usage_count" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "hashtag" ADD "post_count" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "hashtag" ADD "trend_score" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "hashtag" ADD "last_used_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "post_hashtag" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "post_hashtag" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "post_hashtag" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "post_hashtag" ADD "post_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "post_hashtag" ADD "hashtag_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "post" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "post" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "post" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "post" ADD "author_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "post" ADD "like_count" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "post" ADD "reply_count" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "post" ADD "repost_count" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "post" ADD "view_count" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "post" ADD "media_count" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "users" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "users" ADD "first_name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD "avatar_public_id" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD "last_name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD "resource_type" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD "password_hash" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD "email_verified" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "follows" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "follows" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "follows" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "follows" ADD "follower_id" uuid`);
        await queryRunner.query(`ALTER TABLE "follows" ADD "following_id" uuid`);
        await queryRunner.query(`ALTER TABLE "r_like" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "r_like" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "r_like" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "r_like" ADD "user_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "r_like" ADD "post_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "r_like" ADD "reply_id" uuid`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`CREATE TYPE "public"."audit_logs_risk_event_enum" AS ENUM('ABUSE', 'ANOMALY', 'BRUTE_FORCE', 'TOKEN_REUSE', 'RATE_LIMIT_TRIGGERED', 'POSSIBLE_COMPROMISE')`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "risk_event" "public"."audit_logs_risk_event_enum"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "user_id" character varying`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "user_agent" character varying`);
        await queryRunner.query(`CREATE INDEX "IDX_521766c01050bef30e5600c4b2" ON "like" ("created_at") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_3221edd468ef18cc93a806b74b" ON "like" ("post_id", "user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_889e0abce86f466db2488ad739" ON "bookmark" ("user_id", "created_at") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_9835db6ee07225b1b2fad9943e" ON "bookmark" ("post_id", "user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_8e1152672957ae8312354ff22c" ON "mention" ("reply_id", "mentioned_user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_1815b34ed24c6feee36cb66360" ON "mention" ("post_id", "mentioned_user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_6e8df8e05e93dc408065071130" ON "mention" ("mentioned_user_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_7dc106312b0d9f111acf7ca02a" ON "reply" ("author_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_3cf30b2d2c2249ec410b84ecdd" ON "reply" ("post_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_3f023b8dc80e2609d8dce8d22c" ON "repost" ("original_post_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_d2fee25ddac8d9798081cffe7c" ON "repost" ("user_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_dd688373931824f98e4e48f22f" ON "hashtag" ("usage_count") `);
        await queryRunner.query(`CREATE INDEX "IDX_7bd46977fb3fcf634147df2554" ON "post_hashtag" ("post_id", "hashtag_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_ecff676b512e390882cb8b0bcd" ON "post_hashtag" ("hashtag_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_0f8f2f0c0512fbecbe3034b804" ON "post" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_9bf357e95bffead052c455f46c" ON "post" ("author_id", "visibility", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_73bd30a28beb42beffa970d9fe" ON "r_like" ("created_at") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_987cd8ad48504ee8cd7d68b907" ON "r_like" ("reply_id", "user_id") `);
        await queryRunner.query(`ALTER TABLE "follows" ADD CONSTRAINT "UQ_8109e59f691f0444b43420f6987" UNIQUE ("follower_id", "following_id")`);
        await queryRunner.query(`ALTER TABLE "email_tokens" ADD CONSTRAINT "FK_018295f41628791c301bfe8b625" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD CONSTRAINT "FK_3ddc983c5f7bcf132fd8732c3f4" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "like" ADD CONSTRAINT "FK_4356ac2f9519c7404a2869f1691" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "like" ADD CONSTRAINT "FK_d41caa70371e578e2a4791a88ae" FOREIGN KEY ("post_id") REFERENCES "post"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookmark" ADD CONSTRAINT "FK_88d15be9a11888c73c7328a32fc" FOREIGN KEY ("post_id") REFERENCES "post"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookmark" ADD CONSTRAINT "FK_8f1a143c6ba8bba0e2a4f41e0d0" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "media" ADD CONSTRAINT "FK_20dc152fa567df67110b94d6f16" FOREIGN KEY ("post_id") REFERENCES "post"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "media" ADD CONSTRAINT "FK_a06d5fc3cbf364e3f7fe08f1350" FOREIGN KEY ("reply_id") REFERENCES "reply"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mention" ADD CONSTRAINT "FK_1ceda53d50bbc68711ead73632a" FOREIGN KEY ("post_id") REFERENCES "post"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mention" ADD CONSTRAINT "FK_4533a736e6038b6de35d50befae" FOREIGN KEY ("reply_id") REFERENCES "reply"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mention" ADD CONSTRAINT "FK_17edd318132abe43dcc02106d8d" FOREIGN KEY ("mentioned_user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mention" ADD CONSTRAINT "FK_56116d97f4485e37b82685fd9bc" FOREIGN KEY ("author_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reply" ADD CONSTRAINT "FK_26661bdd4c8727e914b5f2b10b5" FOREIGN KEY ("post_id") REFERENCES "post"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reply" ADD CONSTRAINT "FK_0d98e8ade07b472e8af8b856e1b" FOREIGN KEY ("author_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reply" ADD CONSTRAINT "FK_52950ff18c5841b7c67f1504b0f" FOREIGN KEY ("parent_reply_id") REFERENCES "reply"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "repost" ADD CONSTRAINT "FK_2aab7c4ee36af12259c641825b8" FOREIGN KEY ("original_post_id") REFERENCES "post"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "repost" ADD CONSTRAINT "FK_59ab6efd4621bf07bd72e697e82" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post_hashtag" ADD CONSTRAINT "FK_a855b00dfa76d3dd76a554a0e7d" FOREIGN KEY ("post_id") REFERENCES "post"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post_hashtag" ADD CONSTRAINT "FK_44fad00dc75a7ebb2cad8d0bcb1" FOREIGN KEY ("hashtag_id") REFERENCES "hashtag"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post" ADD CONSTRAINT "FK_2f1a9ca8908fc8168bc18437f62" FOREIGN KEY ("author_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "follows" ADD CONSTRAINT "FK_54b5dc2739f2dea57900933db66" FOREIGN KEY ("follower_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "follows" ADD CONSTRAINT "FK_c518e3988b9c057920afaf2d8c0" FOREIGN KEY ("following_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "r_like" ADD CONSTRAINT "FK_619a55ed5c2bb6bb5f4f8e5b499" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "r_like" ADD CONSTRAINT "FK_037704f1b7b083441e47da96cb1" FOREIGN KEY ("reply_id") REFERENCES "reply"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "r_like" DROP CONSTRAINT "FK_037704f1b7b083441e47da96cb1"`);
        await queryRunner.query(`ALTER TABLE "r_like" DROP CONSTRAINT "FK_619a55ed5c2bb6bb5f4f8e5b499"`);
        await queryRunner.query(`ALTER TABLE "follows" DROP CONSTRAINT "FK_c518e3988b9c057920afaf2d8c0"`);
        await queryRunner.query(`ALTER TABLE "follows" DROP CONSTRAINT "FK_54b5dc2739f2dea57900933db66"`);
        await queryRunner.query(`ALTER TABLE "post" DROP CONSTRAINT "FK_2f1a9ca8908fc8168bc18437f62"`);
        await queryRunner.query(`ALTER TABLE "post_hashtag" DROP CONSTRAINT "FK_44fad00dc75a7ebb2cad8d0bcb1"`);
        await queryRunner.query(`ALTER TABLE "post_hashtag" DROP CONSTRAINT "FK_a855b00dfa76d3dd76a554a0e7d"`);
        await queryRunner.query(`ALTER TABLE "repost" DROP CONSTRAINT "FK_59ab6efd4621bf07bd72e697e82"`);
        await queryRunner.query(`ALTER TABLE "repost" DROP CONSTRAINT "FK_2aab7c4ee36af12259c641825b8"`);
        await queryRunner.query(`ALTER TABLE "reply" DROP CONSTRAINT "FK_52950ff18c5841b7c67f1504b0f"`);
        await queryRunner.query(`ALTER TABLE "reply" DROP CONSTRAINT "FK_0d98e8ade07b472e8af8b856e1b"`);
        await queryRunner.query(`ALTER TABLE "reply" DROP CONSTRAINT "FK_26661bdd4c8727e914b5f2b10b5"`);
        await queryRunner.query(`ALTER TABLE "mention" DROP CONSTRAINT "FK_56116d97f4485e37b82685fd9bc"`);
        await queryRunner.query(`ALTER TABLE "mention" DROP CONSTRAINT "FK_17edd318132abe43dcc02106d8d"`);
        await queryRunner.query(`ALTER TABLE "mention" DROP CONSTRAINT "FK_4533a736e6038b6de35d50befae"`);
        await queryRunner.query(`ALTER TABLE "mention" DROP CONSTRAINT "FK_1ceda53d50bbc68711ead73632a"`);
        await queryRunner.query(`ALTER TABLE "media" DROP CONSTRAINT "FK_a06d5fc3cbf364e3f7fe08f1350"`);
        await queryRunner.query(`ALTER TABLE "media" DROP CONSTRAINT "FK_20dc152fa567df67110b94d6f16"`);
        await queryRunner.query(`ALTER TABLE "bookmark" DROP CONSTRAINT "FK_8f1a143c6ba8bba0e2a4f41e0d0"`);
        await queryRunner.query(`ALTER TABLE "bookmark" DROP CONSTRAINT "FK_88d15be9a11888c73c7328a32fc"`);
        await queryRunner.query(`ALTER TABLE "like" DROP CONSTRAINT "FK_d41caa70371e578e2a4791a88ae"`);
        await queryRunner.query(`ALTER TABLE "like" DROP CONSTRAINT "FK_4356ac2f9519c7404a2869f1691"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP CONSTRAINT "FK_3ddc983c5f7bcf132fd8732c3f4"`);
        await queryRunner.query(`ALTER TABLE "email_tokens" DROP CONSTRAINT "FK_018295f41628791c301bfe8b625"`);
        await queryRunner.query(`ALTER TABLE "follows" DROP CONSTRAINT "UQ_8109e59f691f0444b43420f6987"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_987cd8ad48504ee8cd7d68b907"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_73bd30a28beb42beffa970d9fe"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9bf357e95bffead052c455f46c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0f8f2f0c0512fbecbe3034b804"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ecff676b512e390882cb8b0bcd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7bd46977fb3fcf634147df2554"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dd688373931824f98e4e48f22f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d2fee25ddac8d9798081cffe7c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3f023b8dc80e2609d8dce8d22c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3cf30b2d2c2249ec410b84ecdd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7dc106312b0d9f111acf7ca02a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6e8df8e05e93dc408065071130"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1815b34ed24c6feee36cb66360"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8e1152672957ae8312354ff22c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9835db6ee07225b1b2fad9943e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_889e0abce86f466db2488ad739"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3221edd468ef18cc93a806b74b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_521766c01050bef30e5600c4b2"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "user_agent"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "risk_event"`);
        await queryRunner.query(`DROP TYPE "public"."audit_logs_risk_event_enum"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "r_like" DROP COLUMN "reply_id"`);
        await queryRunner.query(`ALTER TABLE "r_like" DROP COLUMN "post_id"`);
        await queryRunner.query(`ALTER TABLE "r_like" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "r_like" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "r_like" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "r_like" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "follows" DROP COLUMN "following_id"`);
        await queryRunner.query(`ALTER TABLE "follows" DROP COLUMN "follower_id"`);
        await queryRunner.query(`ALTER TABLE "follows" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "follows" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "follows" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "email_verified"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "password_hash"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "resource_type"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "last_name"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "avatar_public_id"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "first_name"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "post" DROP COLUMN "media_count"`);
        await queryRunner.query(`ALTER TABLE "post" DROP COLUMN "view_count"`);
        await queryRunner.query(`ALTER TABLE "post" DROP COLUMN "repost_count"`);
        await queryRunner.query(`ALTER TABLE "post" DROP COLUMN "reply_count"`);
        await queryRunner.query(`ALTER TABLE "post" DROP COLUMN "like_count"`);
        await queryRunner.query(`ALTER TABLE "post" DROP COLUMN "author_id"`);
        await queryRunner.query(`ALTER TABLE "post" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "post" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "post" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "post_hashtag" DROP COLUMN "hashtag_id"`);
        await queryRunner.query(`ALTER TABLE "post_hashtag" DROP COLUMN "post_id"`);
        await queryRunner.query(`ALTER TABLE "post_hashtag" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "post_hashtag" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "post_hashtag" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "hashtag" DROP COLUMN "last_used_at"`);
        await queryRunner.query(`ALTER TABLE "hashtag" DROP COLUMN "trend_score"`);
        await queryRunner.query(`ALTER TABLE "hashtag" DROP COLUMN "post_count"`);
        await queryRunner.query(`ALTER TABLE "hashtag" DROP COLUMN "usage_count"`);
        await queryRunner.query(`ALTER TABLE "hashtag" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "hashtag" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "hashtag" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "repost" DROP COLUMN "original_post_id"`);
        await queryRunner.query(`ALTER TABLE "repost" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "repost" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "repost" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "repost" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "reply" DROP COLUMN "parent_reply_id"`);
        await queryRunner.query(`ALTER TABLE "reply" DROP COLUMN "reply_count"`);
        await queryRunner.query(`ALTER TABLE "reply" DROP COLUMN "author_id"`);
        await queryRunner.query(`ALTER TABLE "reply" DROP COLUMN "post_id"`);
        await queryRunner.query(`ALTER TABLE "reply" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "reply" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "reply" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "mention" DROP COLUMN "author_id"`);
        await queryRunner.query(`ALTER TABLE "mention" DROP COLUMN "mentioned_user_id"`);
        await queryRunner.query(`ALTER TABLE "mention" DROP COLUMN "reply_id"`);
        await queryRunner.query(`ALTER TABLE "mention" DROP COLUMN "post_id"`);
        await queryRunner.query(`ALTER TABLE "mention" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "mention" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "mention" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "media" DROP COLUMN "reply_id"`);
        await queryRunner.query(`ALTER TABLE "media" DROP COLUMN "post_id"`);
        await queryRunner.query(`ALTER TABLE "media" DROP COLUMN "resource_type"`);
        await queryRunner.query(`ALTER TABLE "media" DROP COLUMN "media_url"`);
        await queryRunner.query(`ALTER TABLE "media" DROP COLUMN "public_id"`);
        await queryRunner.query(`ALTER TABLE "media" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "media" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "media" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "bookmark" DROP COLUMN "post_id"`);
        await queryRunner.query(`ALTER TABLE "bookmark" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "bookmark" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "bookmark" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "bookmark" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "like" DROP COLUMN "post_id"`);
        await queryRunner.query(`ALTER TABLE "like" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "like" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "like" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "like" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP COLUMN "user_agent"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP COLUMN "last_used_at"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP COLUMN "expires_at"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP COLUMN "hashed_token"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP COLUMN "token_id"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "email_tokens" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "email_tokens" DROP COLUMN "expires_at"`);
        await queryRunner.query(`ALTER TABLE "email_tokens" DROP COLUMN "token_hash"`);
        await queryRunner.query(`ALTER TABLE "email_tokens" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "email_tokens" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "email_tokens" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "userAgent" character varying`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "userId" character varying`);
        await queryRunner.query(`CREATE TYPE "public"."audit_logs_riskevent_enum" AS ENUM('ABUSE', 'ANOMALY', 'BRUTE_FORCE', 'TOKEN_REUSE', 'RATE_LIMIT_TRIGGERED', 'POSSIBLE_COMPROMISE')`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "riskEvent" "public"."audit_logs_riskevent_enum"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "r_like" ADD "postId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "r_like" ADD "userId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "r_like" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "r_like" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "r_like" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "r_like" ADD "replyId" uuid`);
        await queryRunner.query(`ALTER TABLE "follows" ADD "followingId" uuid`);
        await queryRunner.query(`ALTER TABLE "follows" ADD "followerId" uuid`);
        await queryRunner.query(`ALTER TABLE "follows" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "follows" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "follows" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" ADD "firstName" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD "resourceType" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD "passwordHash" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD "lastName" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD "avatarPublicId" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD "emailVerified" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "users" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "users" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "post" ADD "mediaCount" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "post" ADD "viewCount" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "post" ADD "repostCount" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "post" ADD "replyCount" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "post" ADD "likeCount" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "post" ADD "authorId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "post" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "post" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "post" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "post_hashtag" ADD "hashtagId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "post_hashtag" ADD "postId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "post_hashtag" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "post_hashtag" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "post_hashtag" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "hashtag" ADD "usageCount" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "hashtag" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "hashtag" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "hashtag" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "hashtag" ADD "lastUsedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "hashtag" ADD "trendScore" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "hashtag" ADD "postCount" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "repost" ADD "originalPostId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "repost" ADD "userId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "repost" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "repost" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "repost" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "reply" ADD "parentReplyId" uuid`);
        await queryRunner.query(`ALTER TABLE "reply" ADD "replyCount" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "reply" ADD "authorId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "reply" ADD "postId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "reply" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "reply" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "reply" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "mention" ADD "replyId" uuid`);
        await queryRunner.query(`ALTER TABLE "mention" ADD "postId" uuid`);
        await queryRunner.query(`ALTER TABLE "mention" ADD "authorId" uuid`);
        await queryRunner.query(`ALTER TABLE "mention" ADD "mentionedUserId" uuid`);
        await queryRunner.query(`ALTER TABLE "mention" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "mention" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "mention" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "media" ADD "resourceType" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "media" ADD "mediaUrl" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "media" ADD "publicId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "media" ADD "replyId" uuid`);
        await queryRunner.query(`ALTER TABLE "media" ADD "postId" uuid`);
        await queryRunner.query(`ALTER TABLE "media" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "media" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "media" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "bookmark" ADD "userId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "bookmark" ADD "postId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "bookmark" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "bookmark" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "bookmark" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "like" ADD "postId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "like" ADD "userId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "like" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "like" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "like" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD "userAgent" character varying`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD "hashedToken" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD "tokenId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD "userId" uuid`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD "lastUsedAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD "expiresAt" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "email_tokens" ADD "tokenHash" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "email_tokens" ADD "userId" uuid`);
        await queryRunner.query(`ALTER TABLE "email_tokens" ADD "expiresAt" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "email_tokens" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "email_tokens" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "email_tokens" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "follows" ADD CONSTRAINT "UQ_105079775692df1f8799ed0fac8" UNIQUE ("followerId", "followingId")`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_0c2bb4798c44b15d5b92b62b33" ON "r_like" ("userId", "replyId") `);
        await queryRunner.query(`CREATE INDEX "IDX_ab7f82381f392d8c38ec5fc537" ON "r_like" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_333b5b35488ffbf401d0728b46" ON "post" ("createdAt", "visibility", "authorId") `);
        await queryRunner.query(`CREATE INDEX "IDX_fb91bea2d37140a877b775e6b2" ON "post" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_fc550e52604301a6fcc23183e9" ON "post_hashtag" ("createdAt", "hashtagId") `);
        await queryRunner.query(`CREATE INDEX "IDX_d3d78c80aedd7605863b5d1f14" ON "post_hashtag" ("postId", "hashtagId") `);
        await queryRunner.query(`CREATE INDEX "IDX_251105b046faae0f8740ab39cb" ON "hashtag" ("usageCount") `);
        await queryRunner.query(`CREATE INDEX "IDX_07a8923e0c3543fb9c6bc2e35c" ON "repost" ("createdAt", "userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_5c73da33047a8e7f862fbd65c9" ON "repost" ("createdAt", "originalPostId") `);
        await queryRunner.query(`CREATE INDEX "IDX_c5a573b830502bf341d9ec9803" ON "reply" ("createdAt", "postId") `);
        await queryRunner.query(`CREATE INDEX "IDX_2ae88db6d7f193e004ee1d9794" ON "reply" ("createdAt", "authorId") `);
        await queryRunner.query(`CREATE INDEX "IDX_81e9616cb4c5c0f18ec277950b" ON "mention" ("createdAt", "mentionedUserId") `);
        await queryRunner.query(`CREATE INDEX "IDX_f997b5003d8b22a0ec0902e55c" ON "mention" ("mentionedUserId", "postId") `);
        await queryRunner.query(`CREATE INDEX "IDX_ad94e8d3b6b2525d4980f960cd" ON "mention" ("mentionedUserId", "replyId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_9e9632e3b6afa29ac5bb84a5d5" ON "bookmark" ("postId", "userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_b6aae0d8a415c27308fe51c837" ON "bookmark" ("createdAt", "userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_ca9645f823ed33ad823063b35b" ON "like" ("createdAt") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_78a9f4a1b09b6d2bf7ed85f252" ON "like" ("userId", "postId") `);
        await queryRunner.query(`ALTER TABLE "r_like" ADD CONSTRAINT "FK_10ac8c44e53eb105de83c8b63c8" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "r_like" ADD CONSTRAINT "FK_a3ae0bfcdccb98ba91508574eb1" FOREIGN KEY ("replyId") REFERENCES "reply"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "follows" ADD CONSTRAINT "FK_fdb91868b03a2040db408a53331" FOREIGN KEY ("followerId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "follows" ADD CONSTRAINT "FK_ef463dd9a2ce0d673350e36e0fb" FOREIGN KEY ("followingId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post" ADD CONSTRAINT "FK_c6fb082a3114f35d0cc27c518e0" FOREIGN KEY ("authorId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post_hashtag" ADD CONSTRAINT "FK_6b41c908e59dd1c45518efa4291" FOREIGN KEY ("postId") REFERENCES "post"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post_hashtag" ADD CONSTRAINT "FK_5e6bd8131c5321b4dbf68f1ce5f" FOREIGN KEY ("hashtagId") REFERENCES "hashtag"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "repost" ADD CONSTRAINT "FK_1398d4509dfe620c68724aeff30" FOREIGN KEY ("originalPostId") REFERENCES "post"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "repost" ADD CONSTRAINT "FK_d485b70d5447a47d8ebcb815920" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reply" ADD CONSTRAINT "FK_650bb493bc96cdc1c6a95d50ccd" FOREIGN KEY ("postId") REFERENCES "post"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reply" ADD CONSTRAINT "FK_9c7aa85b4b2be67c1b7235d03fe" FOREIGN KEY ("authorId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reply" ADD CONSTRAINT "FK_f0af68fe0e599c7cc7f34699ad5" FOREIGN KEY ("parentReplyId") REFERENCES "reply"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mention" ADD CONSTRAINT "FK_6e47473e7777212acf0f1f10e66" FOREIGN KEY ("postId") REFERENCES "post"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mention" ADD CONSTRAINT "FK_ff19b87c8b552823b87abf5c7af" FOREIGN KEY ("replyId") REFERENCES "reply"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mention" ADD CONSTRAINT "FK_16a2deee0d7ea361950eed1b944" FOREIGN KEY ("mentionedUserId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mention" ADD CONSTRAINT "FK_d2f967c23ec5174f12c53ee6712" FOREIGN KEY ("authorId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "media" ADD CONSTRAINT "FK_9dcde1b1308b5f22f34b8454e28" FOREIGN KEY ("postId") REFERENCES "post"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "media" ADD CONSTRAINT "FK_d9e592b7c68d3aab7582e28a06a" FOREIGN KEY ("replyId") REFERENCES "reply"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookmark" ADD CONSTRAINT "FK_ee4a9b84b65399f9a6581d9a9a5" FOREIGN KEY ("postId") REFERENCES "post"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookmark" ADD CONSTRAINT "FK_e389fc192c59bdce0847ef9ef8b" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "like" ADD CONSTRAINT "FK_e8fb739f08d47955a39850fac23" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "like" ADD CONSTRAINT "FK_3acf7c55c319c4000e8056c1279" FOREIGN KEY ("postId") REFERENCES "post"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD CONSTRAINT "FK_610102b60fea1455310ccd299de" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "email_tokens" ADD CONSTRAINT "FK_0a5e6c81093655b770eabd04600" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
