-- AlterEnum
-- This migration adds more than one value to an enum.
-- With PostgreSQL versions 11 and earlier, this is not possible
-- in a single migration. This can be worked around by creating
-- multiple migrations, each migration adding only one value to
-- the enum.


ALTER TYPE "AuditAction" ADD VALUE 'RATE_LIMIT_EXCEEDED';
ALTER TYPE "AuditAction" ADD VALUE 'RATE_LIMIT_BYPASS_ATTEMPT';
ALTER TYPE "AuditAction" ADD VALUE 'RATE_LIMIT_RESET';
ALTER TYPE "AuditAction" ADD VALUE 'BRUTE_FORCE_ATTEMPT';
ALTER TYPE "AuditAction" ADD VALUE 'REQUEST_THROTTLED';
ALTER TYPE "AuditAction" ADD VALUE 'BOT_DETECTED';
ALTER TYPE "AuditAction" ADD VALUE 'BOT_CHALLENGED';
ALTER TYPE "AuditAction" ADD VALUE 'BOT_BLOCKED';
ALTER TYPE "AuditAction" ADD VALUE 'SUSPICIOUS_ACTIVITY';
ALTER TYPE "AuditAction" ADD VALUE 'MALICIOUS_PAYLOAD_DETECTED';
ALTER TYPE "AuditAction" ADD VALUE 'SQL_INJECTION_ATTEMPT';
ALTER TYPE "AuditAction" ADD VALUE 'XSS_ATTEMPT';
ALTER TYPE "AuditAction" ADD VALUE 'CSRF_ATTEMPT';
ALTER TYPE "AuditAction" ADD VALUE 'IP_BLOCKED';
ALTER TYPE "AuditAction" ADD VALUE 'IP_ALLOWLISTED';
ALTER TYPE "AuditAction" ADD VALUE 'IP_BLACKLISTED';
ALTER TYPE "AuditAction" ADD VALUE 'GEO_BLOCKED';
ALTER TYPE "AuditAction" ADD VALUE 'UNUSUAL_LOCATION_DETECTED';
ALTER TYPE "AuditAction" ADD VALUE 'API_KEY_CREATED';
ALTER TYPE "AuditAction" ADD VALUE 'API_KEY_REVOKED';
ALTER TYPE "AuditAction" ADD VALUE 'API_KEY_ABUSED';
ALTER TYPE "AuditAction" ADD VALUE 'ENDPOINT_ABUSE_DETECTED';
ALTER TYPE "AuditAction" ADD VALUE 'UNUSUAL_ACTIVITY_PATTERN';
ALTER TYPE "AuditAction" ADD VALUE 'ADMIN_LOGIN';
ALTER TYPE "AuditAction" ADD VALUE 'ADMIN_ACTION';
ALTER TYPE "AuditAction" ADD VALUE 'CONFIG_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE 'SECURITY_SETTINGS_CHANGED';
