export enum AuditAction {
  //* Authentication
  SIGNUP = 'SIGNUP',
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  REFRESH_TOKEN_ROTATED = 'REFRESH_TOKEN_ROTATED',
  PASSWORD_RESET_REQUEST = 'PASSWORD_RESET_REQUEST',
  PASSWORD_RESET_COMPLETED = 'PASSWORD_RESET_COMPLETED',
  EMAIL_VERIFICATION_SENT = 'EMAIL_VERIFICATION_SENT',
  EMAIL_VERIFIED = 'EMAIL_VERIFIED',

  //! Security / Risk
  FAILED_LOGIN = 'FAILED_LOGIN',
  REUSED_REFRESH_TOKEN = 'REUSED_REFRESH_TOKEN',
  RATE_LIMITED = 'RATE_LIMITED',
  SUSPICIOUS_ACTIVITY = 'SUSPICIOUS_ACTIVITY',

  //* User
  USER_UPDATED = 'USER_UPDATED',
  USER_ROLE_UPDATED = 'USER_ROLE_UPDATED',
  USER_DELETED = 'USER_DELETED',
  PROFILE_VIEWED = 'PROFILE_VIEWED',

  //* Follows
  USER_FOLLOWED = 'USER_FOLLOWED',
  USER_UNFOLLOWED = 'USER_UNFOLLOWED',
  PROFILE_VIEWED_FOLLOWERS = 'PROFILE_VIEWED_FOLLOWERS',

  //TODO Content
  POST_CREATED = 'POST_CREATED',
  POST_VIEWED = 'POST_VIEWED',
  POST_UPDATED = 'POST_UPDATED',
  POST_DELETED = 'POST_DELETED',
  REPLY_CREATED = 'REPLY_CREATED',
  REPOST_CREATED = 'REPOST_CREATED',
  POST_UNLIKED = 'POST_UNLIKED',
  POST_LIKED = 'POST_LIKED',
  POST_BOOKMARKED = 'POST_BOOKMARKED',
  POST_UNBOOKMARKED = 'POST_UNBOOKMARKED',
  POST_REPOSTED = 'POST_REPOSTED',
  POST_UNREPOSTED = 'POST_UNREPOSTED',
  REPLY_DELETED = 'REPLY_DELETED',
  REPLY_UPDATED = 'REPLY_UPDATED',

  //todo ===> ADMIN ACTIONS ===========
  USER_BANNED = 'USER_BANNED',
  USER_UNBANNED = 'USER_UNBANNED',
  POST_DELETED_BY_ADMIN = 'POST_DELETED_BY_ADMIN',
  POST_RESTORED_BY_ADMIN = 'POST_RESTORED_BY_ADMIN',
}

export enum AuditResource {
  AUTH = 'AUTH',
  USER = 'USER',
  POST = 'POST',
  REPLY = 'REPLY',
  REPOST = 'REPOST',
}

export enum RiskEvent {
  //! Arcjet-aligned risk signals
  ABUSE = 'ABUSE',
  ANOMALY = 'ANOMALY',
  BRUTE_FORCE = 'BRUTE_FORCE',
  TOKEN_REUSE = 'TOKEN_REUSE',
  RATE_LIMIT_TRIGGERED = 'RATE_LIMIT_TRIGGERED',
  POSSIBLE_COMPROMISE = 'POSSIBLE_COMPROMISE',
}
