export enum AuditAction {
  //* Authentication
  SIGNUP = 'SIGNUP',
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  REFRESH_TOKEN_ROTATED = 'REFRESH_TOKEN_ROTATED',
  PASSWORD_RESET_REQUEST = 'PASSWORD_RESET_REQUEST',
  PASSWORD_RESET_COMPLETED = 'PASSWORD_RESET_COMPLETED',
  EMAIL_VERIFICATION_SENT = 'EMAIL_VERIFICATION_SENT',
  EMAIL_VERIFIED = 'EMAIL_VERIFIED',

  //! Security / Risk
  FAILED_LOGIN = 'FAILED_LOGIN',
  REUSED_REFRESH_TOKEN = 'REUSED_REFRESH_TOKEN',
  RATE_LIMITED = 'RATE_LIMITED',

  //* User
  USER_UPDATED = 'USER_UPDATED',
  USER_DELETED = 'USER_DELETED',

  //TODO Content (future social features)
  POST_CREATED = 'POST_CREATED',
  POST_DELETED = 'POST_DELETED',
  REPLY_CREATED = 'REPLY_CREATED',
  REPOST_CREATED = 'REPOST_CREATED',
}

export enum AuditResource {
  AUTH = 'AUTH',
  USER = 'USER',
  POST = 'POST',
  REPLY = 'REPLY',
  REPOST = 'REPOST',
}

export enum RiskEvent {
  //! Arcjet-aligned risk signals
  ABUSE = 'ABUSE',
  ANOMALY = 'ANOMALY',
  BRUTE_FORCE = 'BRUTE_FORCE',
  TOKEN_REUSE = 'TOKEN_REUSE',
  RATE_LIMIT_TRIGGERED = 'RATE_LIMIT_TRIGGERED',
  POSSIBLE_COMPROMISE = 'POSSIBLE_COMPROMISE',
}
